version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
      - classifier_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: imgclass_prod
      MYSQL_ENTRYPOINT_INITDB: ./mysql/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=p4ssw0rd --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - internal
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn classifier.wsgi --reload -b 0.0.0.0:8000"
    volumes:
      - ./:/classifier
    ports:
      - 8000:8000
    networks:
      - internal
    env_file:
      - ./local.env
    depends_on:
      db:
        condition: service_healthy

networks:
  internal:

volumes:
  classifier_db: